version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
